print('Hello World!')
print('What is your name?')
my_name = input()
print('It is good to meet you, ' + my_name)
print('The length of your name is:')
print(len(my_name))
print('What is your age?')
age = input()
print('You will be ' + str(int(age) + 1) + 'in a yuar.')